### ISSUE TITLE
Extract CSS class names and publish CSS class-name docs externally

### ISSUE THREAD

**Issue by bbarker** [labordynamicsinstitute/metajelo-web#6]
Extract CSS class names used by metajelo and publish these on a separate repo; this would allow the github pages of that CSS class-name repo to be the docs generated from the code (which would be some very simple code indeed). But doing this as an actual documented code will guarantee that metajelo-web and metajelo-ui will be in sync with whatever class names and docs are provided.

We could also potentially host default styles in the repo to avoid CSS code duplication; will just need to pull it in during the build process for our own site. For other users who don't want our css, it will be as easy as not including the CSS in their HTML.

@larsvilhuber you can create e.g. "metajelo-css" whenever you want.

**Comment by bbarker** [comment]
@larsvilhuber I now realize you are probably suggesting something along these lines: https://www.geeksforgeeks.org/displaying-xml-using-css/

Certainly that could be done in a more automated fashion (the JS wouldn't even need to know about the class names since the XML doc is styled directly by CSS). However, it wouldn't totally replace what we have in `metajelo-web`, I think, because in `metajelo-ui` we still want isolated fragments that don't correspond to complete XML documents.

**Comment by larsvilhuber** [comment]
@clagoze @bbarker Yes, that is exactly what I had in mind.

**Comment by bbarker** [comment]
Initiated in 65586155d159c28da690b52affa62c203974e09f
